apps/job/urls.py
# Done by Carlos Amaral (2021/02/05)

from django.urls import path, include
from .api import api_search
from . import views

urlpatterns = [
    path('api/search/', api_search, name='api_search'),
    path('search/', views.search, name='search'),
    path('add/', views.add_job, name='add_job'),
    path('<int:job_id>/', views.job_detail, name='job_detail'),
    path('<int:job_id>/edit/', views.edit_job, name='edit_job'),
    path('<int:job_id>/apply_for_job/', views.apply_for_job, name='apply_for_job')
]

programmer_job/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('jobs/', include('apps.job.urls')),
    path('dashboard/', include('apps.userprofile.urls')),
    path('notifications/', include('apps.notification.urls')),
    path('', include('apps.core.urls'))
]

apps/job/models.py
# Done by Carlos Amaral (2021/02/05)

from django.contrib.auth.models import User
from django.db import models

class Job(models.Model):
    SIZE_1_9 = 'size_1_9'
    SIZE_10_49 = 'size_10_49'
    SIZE_50_99 = 'size_50_99'
    SIZE_100 = 'size_100'

    CHOICES_SIZE = (
        (SIZE_1_9, '1-9'),
        (SIZE_10_49, '10-49'),
        (SIZE_50_99, '50-99'),
        (SIZE_100, '100+'),
    )

    ACTIVE = 'active'
    EMPLOYED = 'employed'
    ARCHIVED = 'archived'

    CHOICES_STATUS = (
        (ACTIVE, 'Active'),
        (EMPLOYED, 'Employed'),
        (ARCHIVED, 'Archived')
    )

    title = models.CharField(max_length=255)
    short_description = models.TextField()
    long_description = models.TextField(blank=True, null=True)

    company_name = models.CharField(max_length=255)
    company_address = models.CharField(max_length=255, blank=True, null=True)
    company_zipcode = models.CharField(max_length=255, blank=True, null=True)
    company_place = models.CharField(max_length=255, blank=True, null=True)
    company_country = models.CharField(max_length=255, blank=True, null=True)
    company_size = models.CharField(max_length=20, choices=CHOICES_SIZE, default=SIZE_1_9)

    created_by = models.ForeignKey(User, related_name='jobs', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    changed_at = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=20, choices=CHOICES_STATUS, default=ACTIVE)

    def __str__(self):
        return self.title

class Application(models.Model):
    job = models.ForeignKey(Job, related_name='applications', on_delete=models.CASCADE)
    content = models.TextField()
    experience = models.TextField()

    created_by = models.ForeignKey(User, related_name='applications', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

apps/job/forms.py
# Done by Carlos Amaral (2021/02/07)

from django import forms
from .models import Job, Application

class AddJobForm(forms.ModelForm):
    class Meta:
        model = Job
        fields = ['title', 'short_description', 'long_description', 'company_name', 'company_address', 'company_zipcode', 'company_place', 'company_country', 'company_size']

class ApplicationForm(forms.ModelForm):
    class Meta:
        model = Application
        fields = ['content', 'experience']

apps/job/views.py
# Done by Carlos Amaral (2021/02/05)

from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from .forms import AddJobForm, ApplicationForm
from .models import Job

from apps.notification.utilities import create_notification

def search(request):
    return render(request, 'job/search.html')

def job_detail(request, job_id):
    job = Job.objects.get(pk=job_id)

    return render(request, 'job/job_detail.html', {'job': job})


@login_required
def apply_for_job(request, job_id):
    job = Job.objects.get(pk=job_id)

    if request.method == 'POST':
        form = ApplicationForm(request.POST)

        if form.is_valid():
            application = form.save(commit=False)
            application.job = job
            application.created_by = request.user
            application.save()

            create_notification(request, job.created_by, 'application', extra_id=application.id)

            return redirect('dashboard')

    else:
        form = ApplicationForm()

    return render(request, 'job/apply_for_job.html', {'form': form, 'job': job})


@login_required
def add_job(request):
    if request.method == 'POST':
        form = AddJobForm(request.POST)

        if form.is_valid():
            job = form.save(commit=False)
            job.created_by = request.user
            job.save()

            return redirect('dashboard')
    else:
        form = AddJobForm()

    return render(request, 'job/add_job.html', {'form': form})

@login_required
def edit_job(request, job_id):
    job = get_object_or_404(Job, pk=job_id, created_by=request.user)
    if request.method == 'POST':
        form = AddJobForm(request.POST, instance=job)

        if form.is_valid():
            job = form.save(commit=False)
            job.status = request.POST.get('status')
            job.save()

            return redirect('dashboard')

    else:
        form = AddJobForm(instance=job)

    return render(request, 'job/edit_job.html', {'form': form, 'job': job})

apps/job/templates/job/add_job.html
<!-- Done by Carlos Amaral (2021/02/07) -->

{% extends 'core/base.html' %}

{% block content %}
    <div id="add-job-app">
        <h1 class="title">Add job</h1>

        <form v-on:submit="validateForm" method="post" action=".">
            {% csrf_token %}

            {% if form.errors %}
                {% for error in form.errors %}
                    <div class="notification is-danger">
                        {{ error }}
                    </div>
                {% endfor %}
            {% endif %}

            <div class="notification is-danger" v-if="errors.length">
                <p v-for="error in errors">
                     [[ error ]]
                </p>
            </div>

            <div class="field">
                <label>Title</label>

                <div class="control">
                    <input class="input" type="text" name="title" id="id_title" v-model="title">
                </div>
            </div>

            <div class="field">
                <label>Short description</label>

                <div class="control">
                    <textarea class="textarea" name="short_description" id="id_short_description" v-model="short_description"></textarea>
                </div>
            </div>

            <div class="field">
                <label>Long description</label>

                <div class="control">
                    <textarea class="textarea" name="long_description" id="id_long_description"></textarea>
                </div>
            </div>

            <div class="field">
                <label>Company name</label>

                <div class="control">
                    <input class="input" type="text" name="company_name" id="id_company_name" v-model="company_name">
                </div>
            </div>

            <div class="field">
                <label>Company address</label>

                <div class="control">
                    <input class="input" type="text" name="company_address" id="id_company_address">
                </div>
            </div>

            <div class="field">
                <label>Company zipcode</label>

                <div class="control">
                    <input class="input" type="text" name="company_zipcode" id="id_company_zipcode">
                </div>
            </div>

            <div class="field">
                <label>Company place</label>

                <div class="control">
                    <input class="input" type="text" name="company_place" id="id_company_place">
                </div>
            </div>

            <div class="field">
                <label>Company country</label>

                <div class="control">
                    <input class="input" type="text" name="company_country" id="id_company_country">
                </div>
            </div>

            <div class="field">
                <label>Company size</label>

                <div class="control">
                    <div class="select">
                        <select name="company_size" v-model="company_size">
                            <option value="">Choose size</option>
                            <option value="size_1-9">1-9</option>
                            <option value="size_10-49">10-49</option>
                            <option value="size_50-99">50-99</option>
                            <option value="size_100">100+</option>
                        </select>
                    </div>
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <button class="button is-success">Submit</button>
                </div>
            </div>
        </form>
    </div>
{% endblock content %}

{% block scripts %}
<script>
    const AddJobApp = {
        data() {
            return {
                title: '',
                company_name: '',
                short_description: '',
                company_size: '',
                errors: []
            }
        },
        delimiters: ['[[', ']]'],
        methods: {
            validateForm(e) {
                this.errors = []

                if (this.title === '') {
                    this.errors.push('The title field is missing!')
                }

                if (this.short_description === '') {
                    this.errors.push('The short_description field is missing!')
                }

                if (this.company_name === '') {
                    this.errors.push('The company name field is missing!')    
                }

                if (this.company_size === '') {
                    this.errors.push('The company size field is missing!')
                }

                 if (this.errors.length) {
                    e.preventDefault()

                    return false
                } else {
                    return true   
                }
            }
        }
    }

    Vue.createApp(AddJobApp).mount('#add-job-app');
</script>
{% endblock scripts %}

apps/job/templates/job/apply_for_job.html
<!-- Done by Carlos Amaral (2021/02/07) -->

{% extends 'core/base.html' %}

{% block content %}
    <h1 class="title">Apply for job - {{ job.title }}</h1>

    <form method="post" action=".">
        {% csrf_token %}

        {% if form.errors %}
            {% for error in form.errors %}
                <div class="notification is-danger">
                    {{ error }}
                </div>
            {% endfor %}
        {% endif %}

        <div class="field">
            <label>Content</label>

            <div class="control">
                <textarea class="textarea" name="content" id="id_content"></textarea>
            </div>
        </div>

        <div class="field">
            <label>Experience</label>

            <div class="control">
                <textarea class="textarea" name="experience" id="id_experience"></textarea>
            </div>
        </div>

        <div class="field">
            <div class="control">
                <button class="button is-success">Submit</button>
            </div>
        </div>
    </form>

{% endblock content %}

apps/job/templates/job/edit_job.html
<!-- Done by Carlos Amaral (2021/02/12) -->

{% extends 'core/base.html' %}

{% block content %}
    <div id="edit-job-app">
        <h1 class="title">Edit job</h1>

        <form v-on:submit="validateForm" method="post" action=".">
            {% csrf_token %}

            {% if form.errors %}
                {% for error in form.errors %}
                    <div class="notification is-danger">
                        {{ error }}
                    </div>
                {% endfor %}
            {% endif %}

            <div class="notification is-danger" v-if="errors.length">
                <p v-for="error in errors">
                     [[ error ]]
                </p>
            </div>

            <div class="field">
                <label>Title</label>

                <div class="control">
                    <input class="input" type="text" name="title" id="id_title" v-model="title">
                </div>
            </div>

            <div class="field">
                <label>Short description</label>

                <div class="control">
                    <textarea class="textarea" name="short_description" id="id_short_description" v-model="short_description"></textarea>
                </div>
            </div>

            <div class="field">
                <label>Long description</label>

                <div class="control">
                    <textarea class="textarea" name="long_description" id="id_long_description">{% if job.long_description %}{{ job.long_description }}{% endif %}</textarea>
                </div>
            </div>

            <div class="field">
                <label>Company name</label>

                <div class="control">
                    <input class="input" type="text" name="company_name" id="id_company_name" v-model="company_name">
                </div>
            </div>

            <div class="field">
                <label>Company address</label>

                <div class="control">
                    <input class="input" type="text" name="company_address" id="id_company_address" value="{% if job.company_address %}{{ job.company_address }}{% endif %}">
                </div>
            </div>

            <div class="field">
                <label>Company zipcode</label>

                <div class="control">
                    <input class="input" type="text" name="company_zipcode" id="id_company_zipcode" value="{% if job.company_zipcode %}{{ job.company_zipcode }}{% endif %}">
                </div>
            </div>

            <div class="field">
                <label>Company place</label>

                <div class="control">
                    <input class="input" type="text" name="company_place" id="id_company_place" value="{% if job.company_place %}{{ job.company_place }}{% endif %}">
                </div>
            </div>

            <div class="field">
                <label>Company country</label>

                <div class="control">
                    <input class="input" type="text" name="company_country" id="id_company_country" value="{% if job.company_country %}{{ job.company_country }}{% endif %}">
                </div>
            </div>

            <div class="field">
                <label>Company size</label>

                <div class="control">
                    <div class="select">
                        <select name="company_size" v-model="company_size">
                            <option value="">Choose size</option>
                            <option value="size_1-9">1-9</option>
                            <option value="size_10-49">10-49</option>
                            <option value="size_50-99">50-99</option>
                            <option value="size_100">100+</option>
                        </select>
                    </div>
                </div>
            </div>

            <div class="field">
                <label>Status</label>

                <div class="control">
                    <div class="select">
                        <select name="status">
                            <option value="active"{% if job.status == 'active' %} selected{% endif %}>Active</option>
                            <option value="employed"{% if job.status == 'employed' %} selected{% endif %}>Employed</option>
                            <option value="archived"{% if job.status == 'archived' %} selected{% endif %}>Archived</option>
                        </select>
                    </div>
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <button class="button is-success">Save changes</button>
                </div>
            </div>
        </form>
    </div>
{% endblock content %}

{% block scripts %}
<script>
    const EditJobApp = {
        data() {
            return {
                title: '{{ job.title }}',
                company_name: '{{ job.company_name }}',
                short_description: '{{ job.short_description }}',
                company_size: '{{ job.company_size }}',
                errors: []
            }
        },
        delimiters: ['[[', ']]'],
        methods: {
            validateForm(e) {
                this.errors = []

                if (this.title === '') {
                    this.errors.push('The title field is missing!')
                }

                if (this.short_description === '') {
                    this.errors.push('The short_description field is missing!')
                }

                if (this.company_name === '') {
                    this.errors.push('The company name field is missing!')    
                }

                if (this.company_size === '') {
                    this.errors.push('The company size field is missing!')
                }

                 if (this.errors.length) {
                    e.preventDefault()

                    return false
                } else {
                    return true   
                }
            }
        }
    }

    Vue.createApp(EditJobApp).mount('#edit-job-app');
</script>
{% endblock scripts %}

apps/job/templates/job/job_detail.html
<!-- Done by Carlos Amaral (2021/02/05) -->

{% extends 'core/base.html' %}

{% block content %}
    <h1 class="title">{{ job.title }} ({{ job.get_status_display }})</h1>

    <p class="is-size-4">{{ job.short_description }}</p>

    <p>{{ job.long_description }}</p>

    <b>Company name: </b>{{ job.company_name }}<br>
    {% if job.company_address %} <b>Company address: </b>{{ job.company_address }}<br>{% endif %}
    {% if job.company_zipcode %} <b>Company zipcode: </b>{{ job.company_zipcode }}<br>{% endif %}
    {% if job.company_place %} <b>Company place: </b>{{ job.company_place }}<br>{% endif %}
    {% if job.company_country %} <b>Company country: </b>{{ job.company_country }}<br>{% endif %}
    <b>Company size: </b>{{ job.get_company_size_display }}<br>


    {% if job.status == 'active' %}
    <a href="{% url 'apply_for_job' job.id %}" class="button is-success">Apply for job</a>
    {% else %}
        <p>This job is not available anymore!</p>
    {% endif %}
{% endblock content %}

apps/job/templates/job/search.html
<!-- Done by Carlos Amaral (2021/02/11) -->

{% extends 'core/base.html' %}

{% block content %}
    <div id="search-app">
        <h1 class="title">Search</h1>

        <form @submit.prevent="performSearch()">
            <div class="columns">
                <div class="column is-4">
                    <div class="field">
                        <label>Query</label>

                        <div class="control">
                            <input type="text" name="query" class="input" v-model="query">
                        </div>
                    </div>

                    <div class="field">
                        <label>Company size</label>

                        <div class="control">
                            <div class="select">
                                <select name="company_size" v-model="company_size">
                                    <option value="" selected>All</option>
                                    <option value="size_1-9">1-9</option>
                                    <option value="size_10-49">10-49</option>
                                    <option value="size_50-99">50-99</option>
                                    <option value="size_100">100+</option>
                                </select>
                            </div>
                        </div>
                    </div>

                    <div class="field">
                        <div class="control">
                            <button class="button is-success">Search</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>

        <div v-if="jobs.length">
            <hr>

            <div 
                v-for="job in jobs"
                :key="job.id"
                class="notification mt-2"
            >
                <h3 class="is-size-4">[[ job.title ]]</h3>
                <p>[[ job.company_name ]]</p>

                <a :href="job.url">View details</a>
            </div>
        </div>
    </div>
{% endblock content %}


{% block scripts %}
<script>
    const SearchApp = {
        data() {
            return {
                query: '',
                company_size: '',
                jobs: []
            }    
        },
        delimiters: ['[[', ']]'],
        methods: {
            performSearch() {
                var data = {
                    'query': this.query,
                    'company_size': this.company_size
                }

                fetch('/jobs/api/search/', {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                        'X-CSRFToken': '{{ csrf_token }}'    
                    }, 
                    body: JSON.stringify(data)   
                })
                .then((response) => {
                    return response.json()
                })
                .then((result) => {
                    console.log(result.jobs)
                    this.jobs = result.jobs
                })
                .catch((error) => {
                    console.log('Error', error)
                })

            }
        }
    }

    Vue.createApp(SearchApp).mount('#search-app')
</script>
{% endblock scripts %}